apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: webapp
  namespaceSelector:
    matchNames:
      - development
      - staging
      - production
  endpoints:
  - port: http
    path: /metrics
    interval: 15s