apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
    - port: {{ .Values.webapp.service.port }}
      targetPort: {{ .Values.webapp.service.port }}
      {{- if eq .Values.webapp.service.type "NodePort" }}
      nodePort: {{ .Values.webapp.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "webapp.selectorLabels" . | nindent 4 }}