apiVersion: v2
name: webapp
description: A Helm chart for the K8s Demo Application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mongodb
    version: "12.1.31"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled