webapp:
  name: webapp
  image:
    repository: nanajanashia/k8s-demo-app
    tag: v1.0
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  service:
    type: NodePort
    port: 3000
    nodePort: 30100

serviceAccount:
  create: false
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s
  grafana:
    dashboards:
      enabled: true
  alerts:
    enabled: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

mongodb:
  enabled: true
  auth:
    rootPassword: mongopassword
    username: mongouser
    password: mongopassword
    database: webapp-db

elasticsearchHosts: "http://elasticsearch-master:9200"

service:
  type: LoadBalancer
  port: 5601

resources:
  requests:
    cpu: "100m"
    memory: "500Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"